turing/Turing/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.views.generic.base import RedirectView
from django.conf.urls.static import static

from engine.views import SignUpView, SignUpClosedView

signup_view = SignUpView if settings.REGISTRATION_OPEN else SignUpClosedView

urlpatterns = [
    path('', RedirectView.as_view(url="engine/")),
    path('admin/', admin.site.urls),
    path('engine/', include('engine.urls')),
    path('accounts/signup/', signup_view.as_view(), name='signup'),
    path('accounts/', include('django.contrib.auth.urls'))
]

if settings.DEV_MODE:
    import debug_toolbar
    urlpatterns = [
        path('__debug__/', include(debug_toolbar.urls)),

        # For django versions before 2.0:
        # url(r'^__debug__/', include(debug_toolbar.urls)),

    ] + urlpatterns

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

turing/engine/urls.py
from django.urls import path

from django.conf import settings
from django.conf.urls.static import static

from engine.views import *

app_name = 'engine'

urlpatterns = [
    path('', IndexView.as_view(), name='index'),
    path('gara/new', CreaGaraView.as_view(), name='gara-new'),
    path('gara/upload', UploadGaraView.as_view(), name='gara-upload'),
    path('gara/<int:pk>', GaraView.as_view(), name='gara-detail'),
    path('gara/<int:pk>/admin', GaraAdminView.as_view(), name='gara-admin'),
    path('gara/<int:pk>/parametri', GaraParametriView.as_view(), name='gara-parametri'),
    path('gara/<int:pk>/risposte', GaraRisposteView.as_view(), name='gara-risposte'),
    path('gara/<int:pk>/squadre', GaraSquadreView.as_view(), name='gara-squadre'),
    path('gara/<int:pk>/download', DownloadGaraView.as_view(), name='gara-download'),
    path('gara/<int:pk>/reset', GaraResetView.as_view(), name='gara-reset'),
    path('gara/<int:pk>/delete', GaraDeleteView.as_view(), name='gara-delete'),
    path('gara/<int:pk>/pause', GaraPauseView.as_view(), name='gara-pause'),
    path('gara/<int:pk>/resume', GaraResumeView.as_view(), name='gara-resume'),
    path('query/<int:pk>', QueryView.as_view(), name='query'),
    path('inserisci/<int:pk>', InserimentoView.as_view(), name='inserimento'),
    path('evento/<int:pk>/modifica', ModificaEventoView.as_view(), name='evento-modifica'),
    path('evento/<int:pk>/elimina', EliminaEventoView.as_view(), name='evento-elimina'),
    path('status/<int:pk>', StatusView.as_view(), name='status'),
    path('classifica/<int:pk>/squadre', ClassificaView.as_view(), name='classifica-squadre'),
    path('classifica/<int:pk>/problemi', PuntiProblemiView.as_view(), name='classifica-problemi'),
    path('classifica/<int:pk>/stato', StatoProblemiView.as_view(), name='classifica-stato'),
    path('classifica/<int:pk>/unica', UnicaView.as_view(), name='classifica-unica'),
    path('classifica/<int:pk>/scorrimento', ScorrimentoView.as_view(), name='classifica-scorrimento'),
    path('about', AboutView.as_view(), name="about"),
    path('now', NowView.as_view(), name="now")
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

turing/engine/views.py
from django.views.generic import TemplateView, FormView
from django.views.generic.detail import DetailView
from django.views.generic.edit import CreateView, DeleteView, UpdateView
from django.urls import reverse
from django.contrib import messages
from django.contrib.messages.views import SuccessMessageMixin
from django.contrib.auth.mixins import UserPassesTestMixin, LoginRequiredMixin, PermissionRequiredMixin
from django.http import JsonResponse, HttpResponse
from django.utils import timezone
from django.db import transaction
from django.contrib.auth import login, authenticate
from django import forms
from django.db.models import F

from engine.models import User, Gara, Soluzione, Squadra, Evento, Consegna, Jolly, Bonus
from engine.forms import SignUpForm, RispostaFormset, SquadraFormset, InserimentoForm,\
    ModificaConsegnaForm, ModificaJollyForm, ModificaBonusForm, UploadGaraForm, QueryForm, CreaGaraForm, ModificaGaraForm
from engine.formfields import IntegerMultiField

import logging
logger = logging.getLogger(__name__)


class CheckPermissionsMixin(LoginRequiredMixin, UserPassesTestMixin):
    """
    Mixin che controlla che l'utente sia autenticato e che soddisfi la funzione test_func.
    """
    pass


class IndexView(TemplateView):
    """ Pagina principale """
    template_name = "index.html"


class AboutView(TemplateView):
    """ Pagina 'chi siamo' """
    template_name = "about.html"

class NowView(TemplateView):
    """ Tempo corrente"""
    template_name = "now.html"


class SignUpView(FormView):
    """ Pagina di registrazione """
    form_class = SignUpForm
    template_name = "registration/signup.html"
    success_url = "/engine/"

    def form_valid(self, form):
        user = form.save()
        raw_password = form.cleaned_data.get('password1')
        user = authenticate(username=user.username, password=raw_password)
        login(self.request, user)
        return super().form_valid(form)


class SignUpClosedView(TemplateView):
    """ Pagina per quando la registrazione è disabilitata """
    template_name = "registration/signup_closed.html"


#####################
#    VIEWS GARA     #
#####################

class CreaOModificaGaraView(SuccessMessageMixin):
    """ Superclasse per astrarre metodi comuni a CreaGaraView e GaraParametriView"""
    model = Gara

    def get_form(self):
        form = super().get_form()
        # Cambia i campi per i bonus per avere caselle multiple
        form.fields['fixed_bonus'] = IntegerMultiField(
            required=False, require_all_fields=False,
            help_text=form.fields['fixed_bonus'].help_text,
            label=form.fields['fixed_bonus'].label,
            initial=form.fields['fixed_bonus'].initial)
        form.fields['super_mega_bonus'] = IntegerMultiField(
            required=False, require_all_fields=False,
            help_text=form.fields['super_mega_bonus'].help_text,
            label=form.fields['super_mega_bonus'].label,
            initial=form.fields['super_mega_bonus'].initial)
        return form

    def get_success_url(self, **kwargs):
        return reverse("engine:gara-admin", kwargs={'pk': self.object.pk})


class CreaGaraView(PermissionRequiredMixin, CreaOModificaGaraView, FormView, CreateView):
    """ View per la creazione di una gara """
    form_class = CreaGaraForm
    template_name = "gara/create.html"
    success_message = 'Gara creata con successo!'
    permission_required = "engine.add_gara"

    def get_form_kwargs(self):
        kwargs = super(CreaGaraView, self).get_form_kwargs()
        kwargs['user'] = self.request.user
        return kwargs

    def form_valid(self, form):
        form.instance.admin = self.request.user
        response = super().form_valid(form)
        gara = form.instance
        nomi_squadre = form.cleaned_data.get("nomi_squadre")
        nomi_problemi = form.cleaned_data.get("nomi_problemi")
        risposte_problemi = form.cleaned_data.get("risposte_problemi")
        for (i, nome) in enumerate(nomi_squadre):
            Squadra.objects.create(gara=gara, num=i + 1, nome=nome)
        for i in range(gara.num_problemi):
            Soluzione.objects.create(gara=gara, problema=i + 1, nome=nomi_problemi[i], risposta=risposte_problemi[i])
        return response

    def form_invalid(self, form):
        messages.error(self.request, "Errore: gara non creata correttamente")
        return super().form_invalid(form)


class GaraParametriView(CheckPermissionsMixin, CreaOModificaGaraView, FormView, UpdateView):
    """ View per cambiare i parametri di una gara """
    form_class = ModificaGaraForm
    template_name = "gara/modify.html"
    success_message = 'Parametri di gara salvati con successo!'

    def get_form_kwargs(self):
        kwargs = super().get_form_kwargs()
        kwargs['num_squadre'] = len(self.get_object().squadre.all())
        return kwargs

    def test_func(self):
        # Salva la gara dentro self.object, così siamo sicuri
        # che sia stata validata e non viene chiamato get_object() due volte.
        self.object = self.get_object()
        return self.request.user.can_administrate(self.object)

    @transaction.atomic   # visto che creiamo nuovi problemi E aggiorniamo gara.num_problemi
    def form_valid(self, form):
        gara_nuova = form.instance
        gara_vecchia = self.get_object()

        num_squadre_nuova = form.cleaned_data.get("num_squadre")
        num_squadre_vecchia = len(gara_vecchia.squadre.all())
        num_problemi_nuova = gara_nuova.num_problemi
        num_problemi_vecchia = gara_vecchia.num_problemi

        if num_squadre_nuova > num_squadre_vecchia:
            # dobbiamo creare nuove squadre
            for i in range(num_squadre_vecchia+1, num_squadre_nuova+1):
                Squadra.objects.create(gara=gara_vecchia, num=i, nome="Squadra {}".format(i))
        elif num_squadre_nuova < num_squadre_vecchia:
            # dobbiamo cancellare squadre
            Squadra.objects.filter(gara=gara_vecchia, num__range=(num_squadre_nuova+1, num_squadre_vecchia)).delete()

        if num_problemi_nuova > num_problemi_vecchia:
            # dobbiamo creare nuovi problemi
            for i in range(num_problemi_vecchia+1, num_problemi_nuova+1):
                Soluzione.objects.create(gara=gara_vecchia, problema=i, nome="Problema {}".format(i))
        elif num_problemi_nuova < num_problemi_vecchia:
            # dobbiamo cancellare problemi
            Soluzione.objects.filter(gara=gara_vecchia, problema__range=(num_problemi_nuova+1, num_problemi_vecchia)).delete()

        response = super().form_valid(form) # committa le modifiche
        return response

    def form_invalid(self, form):
        messages.error(self.request, "Errore: parametri di gara non salvati correttamente")
        return super().form_invalid(form)


class GaraView(DetailView):
    """ View con riepilogo di una gara """
    model = Gara
    template_name = "gara/detail.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        if self.request.user.is_authenticated:
            context["can_insert"] = self.request.user.can_insert_gara(self.object)
            context["is_admin"] = self.request.user.can_administrate(self.object)
        return context


class GaraAdminView(CheckPermissionsMixin, DetailView):
    """ View per l'amministrazione di una gara """
    model = Gara
    template_name = "gara/detail_admin.html"

    def test_func(self):
        # Salva la gara dentro self.object, così siamo sicuri
        # che sia stata validata e non viene chiamato get_object() due volte.
        self.object = self.get_object()
        return self.request.user.can_administrate(self.object)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['num_eventi'] = len(self.object.eventi.all())
        return context

    def post(self, request, *args, **kwargs):
        if "inizia" in request.POST:
            loraesatta = timezone.now()
            gara = self.object
            gara.inizio = loraesatta
            gara.save()
        return super().get(self, request)


class GaraRisposteView(CheckPermissionsMixin, SuccessMessageMixin, FormView, DetailView):
    """ View per l'inserimento delle soluzioni esatte di una gara """
    model = Gara
    template_name = 'gara/risposte.html'
    success_message = 'Soluzioni inserite con successo!'

    def test_func(self):
        self.object = self.get_object()
        return self.request.user.can_administrate(self.object)

    def get_success_url(self, **kwargs):
        return reverse("engine:gara-admin", kwargs={'pk': self.object.pk})

    def get_form(self):
        if self.request.POST:
            return RispostaFormset(self.request.POST)
        return RispostaFormset(queryset=Soluzione.objects.filter(gara=self.object))

    def form_valid(self, form):
        form.save()
        return super().form_valid(form)

    def form_invalid(self, form):
        messages.error(self.request, "Errore: soluzioni non inserite correttamente")
        return super().form_invalid(form)


class GaraSquadreView(CheckPermissionsMixin, SuccessMessageMixin, FormView, DetailView):
    """ View per l'inserimento delle squadre partecipanti ad una gara """
    model = Gara
    template_name = 'gara/squadre.html'
    success_message = 'Squadre inserite con successo!'

    def test_func(self):
        self.object = self.get_object()
        return self.request.user.can_administrate(self.object)

    def get_success_url(self, **kwargs):
        return reverse("engine:gara-admin", kwargs={'pk': self.object.pk})

    def get_form(self):
        users = User.objects.all()
        if self.request.POST:
            return SquadraFormset(self.request.POST, users_qs=users)
        return SquadraFormset(queryset=self.object.squadre.all(), users_qs=users)

    def form_valid(self, form):
        for res in form.cleaned_data:

turing/engine/templates/gara/create.html
{% extends "baseheader.html" %}
{% block title %}Crea nuova gara{% endblock %}

{% load crispy_forms_tags %}

{% block content %}

<div class="container">
<h3>Crea una nuova gara</h3>

<form method="post" enctype="multipart/form-data">{% csrf_token %}
    {{ form.non_field_errors }}
    {{ form.errors }}

    {% include 'gara/parametri.html' %}

    <div class="form-row">
        <div class="form-group col-md-12">
        {{ form.nomi_squadre_upload|as_crispy_field }}
        </div>

        <div class="form-group col-md-12">
        {{ form.nomi_problemi_upload|as_crispy_field }}
        </div>

        <div class="form-group col-md-12">
        {{ form.risposte_problemi_upload|as_crispy_field }}
        </div>
    </div>

    <button id="submit" type="submit" class="btn btn-primary">Crea gara</button>
</form>
</div>
{% endblock %}

turing/engine/templates/gara/delete.html
{% extends "basegara.html" %}
{% block title %}{{object.nome}} reset{% endblock %}

{% block content %}
<h3>Gara: <a href="{% url 'engine:gara-detail' object.pk %}">{{ object.nome }}</a> - cancellazione gara</h3>

<p>
È consigliato fare un <a href="{% url 'engine:gara-download' object.pk %}">download</a> dello stato corrente di gara prima di procedere!
</p>
<p>
Questa azione cancellerà la gara, inclusi i suoi parametri di configurazione ed eventuali eventi già avvenuti. Sei sicuro di voler procedere?<br/>
<form method="post">{% csrf_token %}
    <input type="hidden" name="delete" value=1>
    <input type="submit" value="Sì, procedi alla cancellazione della gara!" id="submit">
</form>
</p>

{% endblock %}

turing/engine/templates/gara/detail.html
{% extends "basegara.html" %}
{% load static %}
{% block title %}{{object.nome}}{% endblock %}

{% block css %}<link href="{% static 'engine/css/classifiche.css' %}" rel="stylesheet" type="text/css" >{% endblock %}

{% block content %}
<h3>Gara: {{ object.nome }}  {% if is_admin %}<a href="{% url 'engine:gara-admin' object.pk %}" title="Modifica impostazioni di gara"><i class="fas fa-cogs"></i></a>{% endif %}</h3>

{% if object.inizio is not null and object.sospensione is null %}
    <p>
    Iniziata {{object.inizio}};
    {% if not object.finished %}
        finisce {{object.get_ora_fine}}.</p>
        {% if can_insert %}
        <p>Vai all'<a href="{% url 'engine:inserimento' object.pk %}">inserimento risposte</a>.</p>
        {% endif %}
    {% else %}
        finita {{object.get_ora_fine}}.</p>
    {% endif %}
{% else %}
    {% if object.sospensione is not null %}
<p>Gara temporaneamente sospesa da {{object.sospensione}}</p>
    {% else %}
<p>Gara ancora da iniziare</p>
    {% endif %}
{% endif %}

<h5>Visualizza le classifiche:</h5>

<ul class="pl-0 pl-sm-3 pl-lg-5">
<li class="m-4">
<a class="nohover" href="{% url 'engine:classifica-unica' object.pk %}" target="_blank">
    <b>Visualizzazione unica</b>
</a>
{% if is_admin %}
<ul>
<li>
<a class="nohover" href="{% url 'engine:classifica-unica' object.pk %}?start_pos=2&end_pos=5" target="_blank">
    Visualizzazione unica per un range specifico di posizioni (querystring <code>?start_pos=2&end_pos=5</code>)
</a>
</li>
<li>
<a class="nohover" href="{% url 'engine:classifica-unica' object.pk %}?blink=6" target="_blank">
    Visualizzazione unica con lampeggi per ultime risposte e frecce per cambio posizione (querystring <code>?blink=6</code>)
</a>
</li>
<li>
<a class="nohover" href="{% url 'engine:classifica-unica' object.pk %}?prize=1" target="_blank">
    Visualizzazione unica per premio alla risposta che ha dato il maggior numero di punti, ignorando gli errori (querystring <code>?prize=1</code>)
</a>
</li>
</ul>
{% include 'gara/link_querystring.html' with engine_name='engine:classifica-unica' prefix='Visualizzazione unica' %}
{% endif %}
</li>

<li class="m-4">
<a class="nohover" href="{% url 'engine:classifica-squadre' object.pk %}" target="_blank">
    <b>Punteggi delle squadre</b>
</a>
{% if is_admin %}
{% include 'gara/link_querystring.html' with engine_name='engine:classifica-squadre' prefix='Punteggi delle squadre' %}
{% endif %}
</li>

<li class="m-4">
<a class="nohover" href="{% url 'engine:classifica-problemi' object.pk %}" target="_blank">
    <b>Punteggi dei problemi</b>
</a>
{% if is_admin %}
{% include 'gara/link_querystring.html' with engine_name='engine:classifica-problemi' prefix='Punteggi dei problemi' %}
{% endif %}
</li>

<li class="m-4">
<a class="nohover" href="{% url 'engine:classifica-stato' object.pk %}" target="_blank">
    <b>Stato delle risposte</b>
</a>
{% if is_admin %}
{% include 'gara/link_querystring.html' with engine_name='engine:classifica-stato' prefix='Stato delle risposte' %}
{% endif %}
</li>

<li class="m-4">
<a class="nohover" href="{% url 'engine:classifica-scorrimento' object.pk %}" target="_blank">
    <b>A scorrimento</b>
</a>
{% if is_admin %}
{% include 'gara/link_querystring.html' with engine_name='engine:classifica-scorrimento' prefix='A scorrimento' %}
{% endif %}
</li>
</ul>

{% endblock %}

turing/engine/templates/gara/detail_admin.html
{% extends "basegara.html" %}
{% block title %}{{object.nome}} admin{% endblock %}

{% block content %}
<h3>Gara: <a href="{% url 'engine:gara-detail' object.pk %}">{{ object.nome }}</a></h3>


<h5><a href="{% url 'engine:gara-parametri' object.pk %}"> <i class="fas fa-cog"></i> Parametri</a></h5>
<h5><a href="{% url 'engine:gara-risposte' object.pk %}"> <i class="fas fa-tasks"></i> Soluzioni</a><br/></h5>
<h5><a href="{% url 'engine:gara-squadre' object.pk %}"> <i class="fas fa-users"></i> Squadre</a><br/></h5>
{% if object.inizio is not null and object.sospensione is null %}
<h5><a href="{% url 'engine:query' object.pk %}"> <i class="fas fa-database"></i> Query</a><br/></h5>
{% endif %}

<p>
{% if object.inizio is not null and object.sospensione is null %}
Iniziata {{object.inizio}};
{% if not object.finished %}
finisce {{object.get_ora_fine}}.
{% else %}
finita {{object.get_ora_fine}}.
{% endif %}
</p>

<p>Vai all'<a href="{% url 'engine:inserimento' object.pk %}">inserimento risposte</a>.</p>


{% else %}
    {% if object.sospensione is not null %}
<p>Gara temporaneamente sospesa da {{object.sospensione}}</p>
    {% else %}
<p>
Gara ancora da iniziare<br/>
{% if num_eventi > 0 %}ATTENZIONE! Questa garà già contiene {{ num_eventi }} eventi. Sei sicuro di non dover fare un reset prima di iniziare la gara?<br/>{% endif %}
<form method="post">{% csrf_token %}
    <input type="hidden" name="inizia" value=1>
    <input type="submit" value="Inizia la gara" id="submit">
</form>
</p>
    {% endif %}
{% endif %}

{% endblock %}

turing/engine/templates/gara/inserimento.html
{% extends "basegara.html" %}
{% load static %}

{% load crispy_forms_tags %}
{% block title %}Inserimento {{object.nome}}{% endblock %}

{% block css %}<link href="{% static 'engine/css/inserimento.css' %}" rel="stylesheet" type="text/css" >{% endblock %}

{% block content %}


<div class="container">

<h3>Gara: <a href="{% url 'engine:gara-detail' object.pk %}">{{object.nome}}</a> - inserimento risposte</h3>

<form method="post" id="form-ins">{% csrf_token %}
    {{ form.non_field_errors }}

    <div class="form-row">
        <div class="form-group col-md-12">
        {{ form.squadra|as_crispy_field }}
        </div>
    </div>
    <div class="form-row">
        <div class="col-md-6">
            <div class="form-group">
            {{ form.problema|as_crispy_field }}
            </div>
        </div>
        <div class="col-md-6">
            <div class="form-group">
            {{ form.risposta|as_crispy_field }}
            </div>
        </div>
    </div>
    {% if object.jolly %}{{ form.jolly|as_crispy_field }}{% endif %}
    {% if is_admin %}{{ form.bonus|as_crispy_field }}{% endif %}

    <button id="submit" type="submit" class="btn btn-primary" form="form-ins">Inserisci</button>
</form>
  <div class="card mb-3" style="top: 30px">
    <div class="card-header">
      <i class="fas fa-table"></i>
      Ultime risposte consegnate
    </div>
    <div class="card-body">
      <div class="table-responsive">
        <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
          <thead>
            <tr>
              <th>Id</th>
              <th>Tipo</th>
              <th>Squadra</th>
              <th>Problema</th>
              <th>Valore</th>
              <th>Orario</th>
              <th>Comandi</th>
            </tr>
          </thead>
          <tbody>
              {% for m, e in eventi_recenti %}
            <tr id="event{{e.pk}}">
                <td scope="row">{{e.pk}}</<td>
                <td scope="row">{{e.subclass}}</<td>
                <td scope="row">
                  <span class="event-static">{{e.squadra.get_id_nome}}</span>
                  <select class="event-input" style="max-width: 100%" form="edit{{ e.pk }}" name="squadra">
                    {% for s in squadre_inseribili %}
                    <option value="{{s.pk}}" {% if e.squadra.pk == s.pk %}selected{% endif %}>{{s.get_id_nome}}</option>
                    {% endfor %}
                  </select>
                </td>
                <td scope="row">
                  {% if e.subclass == "Bonus" %}
                  B
                  {% else %}
                  <span class="event-static">{{e.problema}}</span>
                  <input type="number" class="event-input" form="edit{{ e.pk }}" name="problema" value="{{ e.problema }}">
                  {% endif %}
                </td>
                <td scope="row">
                  {% if e.subclass == "Jolly" %}
                  J
                  {% else %}
                  <span class="event-static">{{e.get_valore}}</span>
                  <input type="number" class="event-input" form="edit{{ e.pk }}" name="risposta" value="{{ e.get_valore }}">
                  {% endif %}
                </td>
                <td scope="row">{{e.orario|date:'Y-m-d H:i:s'}}</td>
                <td scope="row">
                {% if m %}
                  <a href="javascript:void(0)" class="event-actions" onclick="$('#event{{ e.pk }}').addClass('editable-event')" id="modifica-{{ e.pk }}">
                      <i class="fas fa-pen-square fa-2x" title="Modifica"></i>&nbsp;&nbsp;</a>
                  <a href="javascript:void(0)" class="event-actions" onclick="$('#event{{ e.pk }}').addClass('deletable-event')" id="elimina-{{ e.pk }}">
                      <i class="fas fa-trash fa-2x" title="Elimina"></i>&nbsp;&nbsp;</a>

                  <form id="edit{{ e.pk }}" class="edit-actions" method="post" action="{% url 'engine:evento-modifica' pk=e.pk %}?redirect_to=engine:inserimento">
                      {% csrf_token %}
                      <a href="javascript:void(0)" onclick="$('#edit{{ e.pk }}').submit();" id="modifica-conferma-{{ e.pk }}"><i class="fas fa-check-circle fa-2x" title="Conferma"></i></a>
                  </form>
                  <a href="javascript:void(0)" class="edit-actions" onclick="$('#event{{ e.pk }}').removeClass('editable-event')" id="modifica-annulla-{{ e.pk }}">
                      <i class="fas fa-times-circle fa-2x" title="Annulla"></i></a>

                  <form id="delete{{ e.pk }}" class="delete-actions" method="post" action="{% url 'engine:evento-elimina' pk=e.pk %}?redirect_to=engine:inserimento">
                      {% csrf_token %}
                      <a href="javascript:void(0)" onclick="$('#delete{{ e.pk }}').submit();" id="elimina-conferma-{{ e.pk }}">
                          <i class="confirm-delete-button fas fa-trash fa-2x" title="Elimina"></i></a>
                  </form>
                  <a href="javascript:void(0)" class="delete-actions" onclick="$('#event{{ e.pk }}').removeClass('deletable-event')" id="elimina-annulla-{{ e.pk }}"><i class="fas fa-times-circle fa-2x" title="Annulla"></i></a>
                {% endif %}
                </td>

            </tr>
            {% endfor %}
          </tbody>
        </table>
      </div>
    </div>
  </div>
</div>

{% endblock %}

turing/engine/templates/gara/modify.html
{% extends "basegara.html" %}
{% block title %}Modifica parametri di gara{% endblock %}

{% block content %}

<div class="container">
<h3>Modifica parametri di gara</h3>

<form method="post" enctype="multipart/form-data">{% csrf_token %}
    {{ form.non_field_errors }}
    {{ form.errors }}

    {% include 'gara/parametri.html' %}

    <button id="submit" type="submit" class="btn btn-primary">Salva modifiche</button>
</form>
</div>
{% endblock %}

turing/engine/templates/gara/pause.html
{% extends "basegara.html" %}
{% block title %}{{object.nome}} reset{% endblock %}

{% block content %}
<h3>Gara: <a href="{% url 'engine:gara-detail' object.pk %}">{{ object.nome }}</a> - sospensione gara</h3>


{% if object.sospensione is null %}
    {% if object.inizio is not null %}
<p>
È consigliato fare un <a href="{% url 'engine:gara-download' object.pk %}">download</a> dello stato corrente di gara prima di procedere!
</p>
<p>
Questa azione metterà in pausa la gara, sospendendo l'inserimento di nuovi eventi e la visualizzazione della classifica. Sei sicuro di voler procedere?<br/>
<form method="post">{% csrf_token %}
    <input type="hidden" name="delete" value=1>
    <input type="submit" value="Sì, procedi alla sospensione della gara!" id="submit">
</form>
</p>
    {% else %}
<p>La gara non è iniziata, e dunque non è nemmeno possibile sospenderla.</p>
    {% endif %}
{% else %}
<p>La gara è già temporaneamente sospesa.</p>
{% endif %}

{% endblock %}

turing/engine/templates/gara/reset.html
{% extends "basegara.html" %}
{% block title %}{{object.nome}} reset{% endblock %}

{% block content %}
<h3>Gara: <a href="{% url 'engine:gara-detail' object.pk %}">{{ object.nome }}</a> - reset gara</h3>

<p>
È consigliato fare un <a href="{% url 'engine:gara-download' object.pk %}">download</a> dello stato corrente di gara prima di procedere!
</p>
<p>
Questa azione cancellerà tutte le consegne, tutti i jolly e tutti i bonus registrati nella gara, e ne azzererà la data ed ora di inizio. Sei sicuro di voler procedere?<br/>
<form method="post">{% csrf_token %}
    <input type="hidden" name="reset" value=1>
    <input type="submit" value="Sì, procedi al reset della gara!" id="submit">
</form>
</p>

{% endblock %}