turing/Turing/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.views.generic.base import RedirectView
from django.conf.urls.static import static

from engine.views import SignUpView, SignUpClosedView

signup_view = SignUpView if settings.REGISTRATION_OPEN else SignUpClosedView

urlpatterns = [
    path('', RedirectView.as_view(url="engine/")),
    path('admin/', admin.site.urls),
    path('engine/', include('engine.urls')),
    path('accounts/signup/', signup_view.as_view(), name='signup'),
    path('accounts/', include('django.contrib.auth.urls'))
]

if settings.DEV_MODE:
    import debug_toolbar
    urlpatterns = [
        path('__debug__/', include(debug_toolbar.urls)),

        # For django versions before 2.0:
        # url(r'^__debug__/', include(debug_toolbar.urls)),

    ] + urlpatterns

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

turing/engine/urls.py
from django.urls import path

from django.conf import settings
from django.conf.urls.static import static

from engine.views import *

app_name = 'engine'

urlpatterns = [
    path('', IndexView.as_view(), name='index'),
    path('gara/new', CreaGaraView.as_view(), name='gara-new'),
    path('gara/upload', UploadGaraView.as_view(), name='gara-upload'),
    path('gara/<int:pk>', GaraView.as_view(), name='gara-detail'),
    path('gara/<int:pk>/admin', GaraAdminView.as_view(), name='gara-admin'),
    path('gara/<int:pk>/parametri', GaraParametriView.as_view(), name='gara-parametri'),
    path('gara/<int:pk>/risposte', GaraRisposteView.as_view(), name='gara-risposte'),
    path('gara/<int:pk>/squadre', GaraSquadreView.as_view(), name='gara-squadre'),
    path('gara/<int:pk>/download', DownloadGaraView.as_view(), name='gara-download'),
    path('gara/<int:pk>/reset', GaraResetView.as_view(), name='gara-reset'),
    path('gara/<int:pk>/delete', GaraDeleteView.as_view(), name='gara-delete'),
    path('gara/<int:pk>/pause', GaraPauseView.as_view(), name='gara-pause'),
    path('gara/<int:pk>/resume', GaraResumeView.as_view(), name='gara-resume'),
    path('query/<int:pk>', QueryView.as_view(), name='query'),
    path('inserisci/<int:pk>', InserimentoView.as_view(), name='inserimento'),
    path('evento/<int:pk>/modifica', ModificaEventoView.as_view(), name='evento-modifica'),
    path('evento/<int:pk>/elimina', EliminaEventoView.as_view(), name='evento-elimina'),
    path('status/<int:pk>', StatusView.as_view(), name='status'),
    path('classifica/<int:pk>/squadre', ClassificaView.as_view(), name='classifica-squadre'),
    path('classifica/<int:pk>/problemi', PuntiProblemiView.as_view(), name='classifica-problemi'),
    path('classifica/<int:pk>/stato', StatoProblemiView.as_view(), name='classifica-stato'),
    path('classifica/<int:pk>/unica', UnicaView.as_view(), name='classifica-unica'),
    path('classifica/<int:pk>/scorrimento', ScorrimentoView.as_view(), name='classifica-scorrimento'),
    path('about', AboutView.as_view(), name="about"),
    path('now', NowView.as_view(), name="now")
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

turing/engine/views.py
from django.views.generic import TemplateView, FormView
from django.views.generic.detail import DetailView
from django.views.generic.edit import CreateView, DeleteView, UpdateView
from django.urls import reverse
from django.contrib import messages
from django.contrib.messages.views import SuccessMessageMixin
from django.contrib.auth.mixins import UserPassesTestMixin, LoginRequiredMixin, PermissionRequiredMixin
from django.http import JsonResponse, HttpResponse
from django.utils import timezone
from django.db import transaction
from django.contrib.auth import login, authenticate
from django import forms
from django.db.models import F

from engine.models import User, Gara, Soluzione, Squadra, Evento, Consegna, Jolly, Bonus
from engine.forms import SignUpForm, RispostaFormset, SquadraFormset, InserimentoForm,\
    ModificaConsegnaForm, ModificaJollyForm, ModificaBonusForm, UploadGaraForm, QueryForm, CreaGaraForm, ModificaGaraForm
from engine.formfields import IntegerMultiField

import logging
logger = logging.getLogger(__name__)


class CheckPermissionsMixin(LoginRequiredMixin, UserPassesTestMixin):
    """
    Mixin che controlla che l'utente sia autenticato e che soddisfi la funzione test_func.
    """
    pass


class IndexView(TemplateView):
    """ Pagina principale """
    template_name = "index.html"


class AboutView(TemplateView):
    """ Pagina 'chi siamo' """
    template_name = "about.html"

class NowView(TemplateView):
    """ Tempo corrente"""
    template_name = "now.html"


class SignUpView(FormView):
    """ Pagina di registrazione """
    form_class = SignUpForm
    template_name = "registration/signup.html"
    success_url = "/engine/"

    def form_valid(self, form):
        user = form.save()
        raw_password = form.cleaned_data.get('password1')
        user = authenticate(username=user.username, password=raw_password)
        login(self.request, user)
        return super().form_valid(form)


class SignUpClosedView(TemplateView):
    """ Pagina per quando la registrazione è disabilitata """
    template_name = "registration/signup_closed.html"


#####################
#    VIEWS GARA     #
#####################

class CreaOModificaGaraView(SuccessMessageMixin):
    """ Superclasse per astrarre metodi comuni a CreaGaraView e GaraParametriView"""
    model = Gara

    def get_form(self):
        form = super().get_form()
        # Cambia i campi per i bonus per avere caselle multiple
        form.fields['fixed_bonus'] = IntegerMultiField(
            required=False, require_all_fields=False,
            help_text=form.fields['fixed_bonus'].help_text,
            label=form.fields['fixed_bonus'].label,
            initial=form.fields['fixed_bonus'].initial)
        form.fields['super_mega_bonus'] = IntegerMultiField(
            required=False, require_all_fields=False,
            help_text=form.fields['super_mega_bonus'].help_text,
            label=form.fields['super_mega_bonus'].label,
            initial=form.fields['super_mega_bonus'].initial)
        return form

    def get_success_url(self, **kwargs):
        return reverse("engine:gara-admin", kwargs={'pk': self.object.pk})


class CreaGaraView(PermissionRequiredMixin, CreaOModificaGaraView, FormView, CreateView):
    """ View per la creazione di una gara """
    form_class = CreaGaraForm
    template_name = "gara/create.html"
    success_message = 'Gara creata con successo!'
    permission_required = "engine.add_gara"

    def get_form_kwargs(self):
        kwargs = super(CreaGaraView, self).get_form_kwargs()
        kwargs['user'] = self.request.user
        return kwargs

    def form_valid(self, form):
        form.instance.admin = self.request.user
        response = super().form_valid(form)
        gara = form.instance
        nomi_squadre = form.cleaned_data.get("nomi_squadre")
        nomi_problemi = form.cleaned_data.get("nomi_problemi")
        risposte_problemi = form.cleaned_data.get("risposte_problemi")
        for (i, nome) in enumerate(nomi_squadre):
            Squadra.objects.create(gara=gara, num=i + 1, nome=nome)
        for i in range(gara.num_problemi):
            Soluzione.objects.create(gara=gara, problema=i + 1, nome=nomi_problemi[i], risposta=risposte_problemi[i])
        return response

    def form_invalid(self, form):
        messages.error(self.request, "Errore: gara non creata correttamente")
        return super().form_invalid(form)


class GaraParametriView(CheckPermissionsMixin, CreaOModificaGaraView, FormView, UpdateView):
    """ View per cambiare i parametri di una gara """
    form_class = ModificaGaraForm
    template_name = "gara/modify.html"
    success_message = 'Parametri di gara salvati con successo!'

    def get_form_kwargs(self):
        kwargs = super().get_form_kwargs()
        kwargs['num_squadre'] = len(self.get_object().squadre.all())
        return kwargs

    def test_func(self):
        # Salva la gara dentro self.object, così siamo sicuri
        # che sia stata validata e non viene chiamato get_object() due volte.
        self.object = self.get_object()
        return self.request.user.can_administrate(self.object)

    @transaction.atomic   # visto che creiamo nuovi problemi E aggiorniamo gara.num_problemi
    def form_valid(self, form):
        gara_nuova = form.instance
        gara_vecchia = self.get_object()

        num_squadre_nuova = form.cleaned_data.get("num_squadre")
        num_squadre_vecchia = len(gara_vecchia.squadre.all())
        num_problemi_nuova = gara_nuova.num_problemi
        num_problemi_vecchia = gara_vecchia.num_problemi

        if num_squadre_nuova > num_squadre_vecchia:
            # dobbiamo creare nuove squadre
            for i in range(num_squadre_vecchia+1, num_squadre_nuova+1):
                Squadra.objects.create(gara=gara_vecchia, num=i, nome="Squadra {}".format(i))
        elif num_squadre_nuova < num_squadre_vecchia:
            # dobbiamo cancellare squadre
            Squadra.objects.filter(gara=gara_vecchia, num__range=(num_squadre_nuova+1, num_squadre_vecchia)).delete()

        if num_problemi_nuova > num_problemi_vecchia:
            # dobbiamo creare nuovi problemi
            for i in range(num_problemi_vecchia+1, num_problemi_nuova+1):
                Soluzione.objects.create(gara=gara_vecchia, problema=i, nome="Problema {}".format(i))
        elif num_problemi_nuova < num_problemi_vecchia:
            # dobbiamo cancellare problemi
            Soluzione.objects.filter(gara=gara_vecchia, problema__range=(num_problemi_nuova+1, num_problemi_vecchia)).delete()

        response = super().form_valid(form) # committa le modifiche
        return response

    def form_invalid(self, form):
        messages.error(self.request, "Errore: parametri di gara non salvati correttamente")
        return super().form_invalid(form)


class GaraView(DetailView):
    """ View con riepilogo di una gara """
    model = Gara
    template_name = "gara/detail.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        if self.request.user.is_authenticated:
            context["can_insert"] = self.request.user.can_insert_gara(self.object)
            context["is_admin"] = self.request.user.can_administrate(self.object)
        return context


class GaraAdminView(CheckPermissionsMixin, DetailView):
    """ View per l'amministrazione di una gara """
    model = Gara
    template_name = "gara/detail_admin.html"

    def test_func(self):
        # Salva la gara dentro self.object, così siamo sicuri
        # che sia stata validata e non viene chiamato get_object() due volte.
        self.object = self.get_object()
        return self.request.user.can_administrate(self.object)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['num_eventi'] = len(self.object.eventi.all())
        return context

    def post(self, request, *args, **kwargs):
        if "inizia" in request.POST:
            loraesatta = timezone.now()
            gara = self.object
            gara.inizio = loraesatta
            gara.save()
        return super().get(self, request)


class GaraRisposteView(CheckPermissionsMixin, SuccessMessageMixin, FormView, DetailView):
    """ View per l'inserimento delle soluzioni esatte di una gara """
    model = Gara
    template_name = 'gara/risposte.html'
    success_message = 'Soluzioni inserite con successo!'

    def test_func(self):
        self.object = self.get_object()
        return self.request.user.can_administrate(self.object)

    def get_success_url(self, **kwargs):
        return reverse("engine:gara-admin", kwargs={'pk': self.object.pk})

    def get_form(self):
        if self.request.POST:
            return RispostaFormset(self.request.POST)
        return RispostaFormset(queryset=Soluzione.objects.filter(gara=self.object))

    def form_valid(self, form):
        form.save()
        return super().form_valid(form)

    def form_invalid(self, form):
        messages.error(self.request, "Errore: soluzioni non inserite correttamente")
        return super().form_invalid(form)


class GaraSquadreView(CheckPermissionsMixin, SuccessMessageMixin, FormView, DetailView):
    """ View per l'inserimento delle squadre partecipanti ad una gara """
    model = Gara
    template_name = 'gara/squadre.html'
    success_message = 'Squadre inserite con successo!'

    def test_func(self):
        self.object = self.get_object()
        return self.request.user.can_administrate(self.object)

    def get_success_url(self, **kwargs):
        return reverse("engine:gara-admin", kwargs={'pk': self.object.pk})

    def get_form(self):
        users = User.objects.all()
        if self.request.POST:
            return SquadraFormset(self.request.POST, users_qs=users)
        return SquadraFormset(queryset=self.object.squadre.all(), users_qs=users)

    def form_valid(self, form):
        for res in form.cleaned_data:

turing/engine/templates/classifiche/class_template.html
{% extends "base.html" %}
{% load static %}

{% block head %}
<script src="{% static "engine/js/client.js" %}"></script>
{% endblock %}

{% block css %}<link href="{% static 'engine/css/classifiche.css' %}" rel="stylesheet" type="text/css" >{% endblock %}

{% block content %}
{% if object.inizio is not null and object.sospensione is null %}
{% block main %}{% endblock %}

<script>
document.updated = false;
document.client = null;
document.addEventListener("updated", function(e) {
  document.updated = true;
});

// Funzioni ausiliare per la conversione dei tempi
function integer_to_elapsed_time(seconds) {
    return new Date(seconds * 1000).toISOString().slice(11, 19);
}

function elapsed_time_to_integer(elapsed) {
    return elapsed.split(':').reduce((acc,time) => (60 * acc) + +time);
}

// Classe per leggere l'ora corrente dal server, anziché dal client
class ServerDate {
    static now() {
        const request = new XMLHttpRequest();
        request.open("GET", "/engine/now", false); // `false` makes the request synchronous
        request.send(null);

        if (request.status === 200) {
            var time_server = Date.parse(request.responseText.trim());
            var time_client = Date.now();
            console.log('Client time', time_client, '- server time', time_server, '- offset', time_client - time_server, 'milliseconds');
            return time_server;
        }
        return null;
    }
}

// Classe ausiliaria per traslare il tempo corrente in un tempo di gara
class ServerDateWithOffset {
    /*
    Nei disegni seguenti:
     - ===== rappresenta istanti di tempo durante la gara
     - ----- rappresenta istanti di tempo prima o dopo la gara
     - ..... rappresenta istanti di tempo in cui la pagina web
             classifica è aperta
     - I è la data di inizio della gara, F la data di fine;


    Durante la gara, apriamo la pagina del browser all'istante A (apertura)
    tipicamente poco dopo l'istante I.
    Con I e A fissati, il browser aggiorna periodicamente il valore del tempo
    corrente sul server, che chiameremo S.
    Graficamente la situazione è rappresentata da:

     ------|==|===========|===============|-------------------------------------->
           I  A...........S               F

     Il tempo corrente di gara G è chiaramente S.

     Dopo la gara, immaginiamoci di voler rivedere lo svolgersi dal vivo della gara
     come se fossimo all'istante R (per replay). La lettera S indica ancora il valore
     corrente dell'orologio sul server, che ovviamente sarà maggiore di F, e quindi
     da traslare ai fini del calcolo del punteggio. Graficamente

     ------|=====|========================|----------------|-----------|--------->
           I     R                        F                A...........S
                 ^<<<<< A deve essere trasformato in R <<<<V

     Il tempo corrente di gara è quindi I + (R - I) + (S - A).

     Nel caso di questo script, l'utente passa come argomento race_time
     il valore dR := R - I. La formula finale è quindi I + (dR + (S - A)).
     */
    constructor(race_time, time_load_page) {
        this.race_time = race_time;
        this.time_load_page = time_load_page;
        this.inizio = null;
    }

    init(inizio) {
        this.inizio = inizio;
    }

    now() {
        return this.inizio + (this.race_time + (ServerDate.now() - this.time_load_page));
    }
}

// Analogo della classe precedente nel caso di gara in corso.
class ServerDateWithoutOffset {
    init(inizio_unused) {
        // La firma prevede di passare il parametro inizio per simmetria con il caso con offset,
        // ma non lo utilizza davvero.
    }

    now() {
        return ServerDate.now();
    }
}

$(document).ready(function() {
    var time_load_page = ServerDate.now();

    {% if race_time is None %}
    var timer = new ServerDateWithoutOffset();
    {% else %}
    var timer = new ServerDateWithOffset({{ race_time }} * 1000, time_load_page);
    {% endif %}

    var url = "{% url 'engine:status' object.pk %}";
    var client = new ClassificaClient(url, '{% block class_type %}{% endblock %}', timer);
    client.init();
    document.client = client;

    {% if ended %}
    var maxElapsedTime =  Math.min(
        Math.floor(time_load_page / 1000 - {{ object.inizio | date:"U" }}),
        elapsed_time_to_integer("{{object.durata}}"));
    $("#myRange").attr("max", maxElapsedTime);
        {% if race_time is None %}
    $("#myRange").val(maxElapsedTime);
    $("#elapsedTimeText").val(integer_to_elapsed_time(maxElapsedTime));
        {% else %}
    $("#myRange").val({{ race_time }});
    $("#elapsedTimeText").val(integer_to_elapsed_time({{ race_time }}));
        {% endif %}
    $("#myRange").on('input', function() {
        var elapsedTime = this.value;
        elapsedTimeText.value = integer_to_elapsed_time(elapsedTime);
        client.progress = client.gara.inizio.getTime() + elapsedTime * 1000;
    });
    $("#elapsedTimeText").on('blur', function() {
        var elapsedTime = elapsed_time_to_integer(this.value);
        myRange.value = elapsedTime;
        client.progress = client.gara.inizio.getTime() + elapsedTime * 1000;
    });
    $("#play").click(function() {
        client.toggleReplay(this, "myRange")
    });
    {% else %}
    setInterval(function() {client.update()}, {{ computation_rate }} * 1000);
    {% endif %}
});

</script>
{% else %}
    {% if object.sospensione is not null %}
<p>La classifica non è disponibile in caso di sospensione della gara</p>
    {% else %}
<p>La classifica non è disponibile prima dell'inizio della gara</p>
    {% endif %}
{% endif %}
{% endblock %}

turing/engine/templates/classifiche/punti_problemi.html
{% extends "classifiche/class_template.html" %}

{% block title %}Problemi {{object.nome}}{% endblock %}

{% block class_type %}problemi{% endblock %}

{% block main %}
<div class="container">
    <h3>Gara: <a href="{% url 'engine:gara-detail' object.pk %}">{{object.nome}}</a> - punteggio problemi</h3>

    <div class="row no-gutters justify-content-end">
        <h3 id="orologio">##:##:##</h3>
    </div>
    <table class="table table-borderless table-sm">
    {% for s in soluzioni %}
    <tr class="row">
        <td class="col-7 col-sm-4 col-lg-2 text-truncate font-weight-bold"><span id="label-{{s.problema}}"></span></span></td>
        <td class="col-sm-8 col-lg-10 small-padding d-none d-sm-block">
            <div class="progress">
                <div id="punti-{{s.problema}}" class="progress-bar progress-bar-light" role="progressbar" aria-valuenow="0" aria-valuemin="0" aria-valuemax="100" style="animation-direction:reverse"><span id="label-punti-{{s.problema}}" class="points-value"></span></div>
                <div id="bonus-{{s.problema}}" class="progress-bar bg-warning" role="progressbar" aria-valuenow="0" aria-valuemin="0" aria-valuemax="100"><span id="label-bonus-{{s.problema}}" class="points-value"></span></div>
            </div>
        </td>
        <td class="col-5 d-sm-none small-padding" >
            <span id="label-punti-mobile-{{s.problema}}" class="points-value">0</span>
        </td>
    </tr>
    {% endfor %}
    </table>

    {% include 'classifiche/replay_control.html' %}
</div>
{% endblock %}

turing/engine/templates/classifiche/replay_control.html
    {% if ended %}
    <div class="row pt-3 no-gutters" id="replayControl">
        <input type="range" min="0" max="0" value="0" id="myRange">
        <button id="play" class="ml-2"><i class="fas fa-play"></i></button>
        <input value="00:00:00" id="elapsedTimeText">
    </div>
    {% endif %}

turing/engine/templates/classifiche/scorrimento.html
{% extends "classifiche/class_template.html" %}

{% block title %}Schermata a scorrimento {{object.nome}}{% endblock %}

{% block class_type %}scorrimento{% endblock %}

{% block main %}
<h3>Gara: <a href="{% url 'engine:gara-detail' object.pk %}">{{object.nome}}</a> - visualizzazione a scorrimento</h3>
<div class="container-fluid">
  <div class="row no-gutters justify-content-end">
      <h3 id="orologio">##:##:##</h3>
  </div>
    {% for sq in object.get_squadre_order %}
    <div class="table-responsive" style="height: 150vh;" id="card-{{sq.num}}">
    <table class="table table-striped table-bordered table-sm maybe-fixed text-center">
        <tbody>
            <tr id="header-{{sq.num}}">
              <th scope="row" style="width: 15%; height: 15vh; vertical-align: middle; font-size: xx-large; white-space:pre" id="pos-{{sq.num}}">°</th>
              <th scope="row" class="squadra" style="width: 70%; height: 15vh; vertical-align: middle; font-size: xx-large; white-space:pre" id="nome-{{sq.num}}"></th>
              <th scope="row" style="display: none;" id="num-{{sq.num}}">{{sq.num}}</th>
              <th scope="row" style="width: 15%; height: 15vh; vertical-align: middle; font-size: xx-large; white-space:pre" id="punt-{{sq.num}}"></th>
            </tr>
        </tbody>
    </table>
    <table class="table table-striped table-bordered table-sm maybe-fixed text-center">
        <thead class="thead-light"><tr>
            {% for s in soluzioni %}
            <th scope="col" style="white-space:pre; height: 10vh; vertical-align: middle;" id="pr-{{s.problema}}-{{sq.num}}">#{{s.problema|stringformat:"02d"}}</th>
            {% endfor %}
            <th scope="col" style="white-space:pre; height: 10vh; vertical-align: middle;" id="pr-bonus-{{sq.num}}">&#xb1;</th>
        </tr></thead>
        <tbody>
            <tr id="riga-{{sq.num}}">
                {% for s in soluzioni %}
                  <td id="cell-{{sq.num}}-{{s.problema}}" style="height: 10vh; vertical-align: middle;"></td>
                {% endfor %}
                <td id="cell-{{sq.num}}-bonus" style="height: 10vh; vertical-align: middle;" class="bonus"></td>
            </tr>
        </tbody>
    </table>
    </div>
    {% endfor %}

    {% include 'classifiche/replay_control.html' %}
</div>
{% endblock %}

turing/engine/templates/classifiche/squadre.html
{% extends "classifiche/class_template.html" %}

{% block title %}Classifica {{object.nome}}{% endblock %}

{% block class_type %}squadre{% endblock %}

{% block main %}
<h3>Gara: <a href="{% url 'engine:gara-detail' object.pk %}">{{object.nome}}</a> - classifica</h3>
<div class="container-fluid">
    <div class="row no-gutters justify-content-end">
        <h3 id="orologio">##:##:##</h3>
    </div>
    <div class="row" id="classifica-container" style="position: relative">
        <table class="table table-borderless">
        {% for sq in object.get_squadre_order %}
        <tr class="row no-gutters">
            <td class="col-7 col-sm-4 col-lg-2 small-padding text-truncate font-weight-bold">
                <span id="label-pos-{{sq.num}}" style="display: inline-block; min-width: 3em;"></span>
                <span id="label-{{sq.num}}">{{sq.nome}}</span>
            </td>
            <td class="col-sm-8 col-lg-10 small-padding d-none d-sm-block" >
                <div class="progress">
                    <div id="team-{{sq.num}}" class="progress-bar{% if sq.ospite %} ospite{% endif %}" style="width:50%" role="progressbar" aria-valuenow="0" aria-valuemin="0" aria-valuemax="100"><span id="label-points-{{sq.num}}" class="points-value">0</span></div>
                </div>
            </td>
            <td class="col-5 d-sm-none small-padding" >
                <span id="label-points-mobile-{{sq.num}}" class="points-value">0</span>
            </td>
        </tr>
        {% endfor %}

        </table>
    </div>

    {% include 'classifiche/replay_control.html' %}
</div>
{% endblock %}

turing/engine/templates/classifiche/stato_problemi.html
{% extends "classifiche/class_template.html" %}

{% block title %}Stato {{object.nome}}{% endblock %}

{% block class_type %}stato{% endblock %}

{% block main %}
<h3>Gara: <a href="{% url 'engine:gara-detail' object.pk %}">{{ object.nome }}</a> - Stato problemi</h3>

<div class="container-fluid">
    <div class="row no-gutters justify-content-end">
        <h3 id="orologio">##:##:##</h3>
    </div>
    <div class="table-responsive">
    <table class="table table-striped table-bordered table-sm maybe-fixed text-center">
        <thead class="thead-light"><tr>
            <th scope="col" style="width:10%">Sq.</th>
            {% for s in soluzioni %}
            <th scope="col">#{{s.problema|stringformat:"02d"}}</th>
            {% endfor %}
        </tr></thead>
        <tbody>
            {% for sq in object.get_squadre_order %}
            <tr id="riga-{{sq.num}}">
                <th scope="row" class="text-truncate squadra {% if sq.ospite %}text-muted{% endif %}">{{sq.nome}}</th>
                {% for s in soluzioni %}
                  <td id="cell-{{sq.num}}-{{s.problema}}"></td>
                {% endfor %}
            </tr>
            {% endfor %}
        </tbody>
    </table>
    </div>

    {% include 'classifiche/replay_control.html' %}
</div>
{% endblock %}

turing/engine/templates/classifiche/unica.html
{% extends "classifiche/class_template.html" %}

{% block title %}Schermata unica {{object.nome}}{% endblock %}

{% block class_type %}unica{% endblock %}

{% block main %}
<h3>Gara: <a href="{% url 'engine:gara-detail' object.pk %}">{{object.nome}}</a> - visualizzazione unica</h3>
<div class="container-fluid">
  <div class="row no-gutters justify-content-end">
      <h3 id="orologio">##:##:##</h3>
  </div>
    <div class="table-responsive">
    <table class="table table-striped table-bordered table-sm maybe-fixed text-center">
        <thead class="thead-light"><tr>
            <th scope="col" style="width:2.5%">Pos.</th>
            <th scope="col" style="display: none; width:2.5%" id="freccia-head"></th>
            <th scope="col" style="width:8%">Squadra</th>
            <th scope="col" style="display: none;">Num. squadra</th>
            <th scope="col" style="width:3%">Punt.</th>
            {% for s in soluzioni %}
            <th scope="col" style="white-space:pre" id="pr-{{s.problema}}">#{{s.problema|stringformat:"02d"}}</th>
            {% endfor %}
            <th scope="col" style="white-space:pre" id="pr-bonus">&#xb1;</th>
        </tr></thead>
        <tbody>
            {% for sq in object.get_squadre_order %}
            {% if sq.num >= start_pos and sq.num <= end_pos %}
            <tr id="riga-{{sq.num}}">
            {% else %}
            <tr id="riga-{{sq.num}}" style="display: none;" >
            {% endif %}
              <th scope="row" style="white-space:pre" id="pos-{{sq.num}}">°</th>
              <th scope="row" style="display: none;" id="freccia-{{sq.num}}"></th>
              <th scope="row" class="text-truncate squadra" style="white-space:pre" id="nome-{{sq.num}}"></th>
              <th scope="row" style="display: none;" id="num-{{sq.num}}">{{sq.num}}</th>
              <th scope="row" style="white-space:pre" id="punt-{{sq.num}}"></th>
                {% for s in soluzioni %}
                  <td id="cell-{{sq.num}}-{{s.problema}}"></td>
                {% endfor %}
                <td id="cell-{{sq.num}}-bonus" class="bonus"></td>
            </tr>
            {% endfor %}
        </tbody>
        <thead class="thead-light"><tr>
            <th scope="row"></th>
            <th scope="row" style="display: none;" id="freccia-foot"></th>
            <th scope="row"></th>
            <th scope="row" style="display: none;"></th>
            <th scope="row"></th>
            {% for s in soluzioni %}
            <td class="progress-bar-zero unica_giuste" id="giuste-{{s.problema}}"></td>
            {% endfor %}
            <th scope="row"></th>
        </tr></thead>
    </table>
    </div>

    {% include 'classifiche/replay_control.html' %}
</div>
{% endblock %}