turing/Turing/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.views.generic.base import RedirectView
from django.conf.urls.static import static

from engine.views import SignUpView, SignUpClosedView

signup_view = SignUpView if settings.REGISTRATION_OPEN else SignUpClosedView

urlpatterns = [
    path('', RedirectView.as_view(url="engine/")),
    path('admin/', admin.site.urls),
    path('engine/', include('engine.urls')),
    path('accounts/signup/', signup_view.as_view(), name='signup'),
    path('accounts/', include('django.contrib.auth.urls'))
]

if settings.DEV_MODE:
    import debug_toolbar
    urlpatterns = [
        path('__debug__/', include(debug_toolbar.urls)),

        # For django versions before 2.0:
        # url(r'^__debug__/', include(debug_toolbar.urls)),

    ] + urlpatterns

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

turing/engine/urls.py
from django.urls import path

from django.conf import settings
from django.conf.urls.static import static

from engine.views import *

app_name = 'engine'

urlpatterns = [
    path('', IndexView.as_view(), name='index'),
    path('gara/new', CreaGaraView.as_view(), name='gara-new'),
    path('gara/upload', UploadGaraView.as_view(), name='gara-upload'),
    path('gara/<int:pk>', GaraView.as_view(), name='gara-detail'),
    path('gara/<int:pk>/admin', GaraAdminView.as_view(), name='gara-admin'),
    path('gara/<int:pk>/parametri', GaraParametriView.as_view(), name='gara-parametri'),
    path('gara/<int:pk>/risposte', GaraRisposteView.as_view(), name='gara-risposte'),
    path('gara/<int:pk>/squadre', GaraSquadreView.as_view(), name='gara-squadre'),
    path('gara/<int:pk>/download', DownloadGaraView.as_view(), name='gara-download'),
    path('gara/<int:pk>/reset', GaraResetView.as_view(), name='gara-reset'),
    path('gara/<int:pk>/delete', GaraDeleteView.as_view(), name='gara-delete'),
    path('gara/<int:pk>/pause', GaraPauseView.as_view(), name='gara-pause'),
    path('gara/<int:pk>/resume', GaraResumeView.as_view(), name='gara-resume'),
    path('query/<int:pk>', QueryView.as_view(), name='query'),
    path('inserisci/<int:pk>', InserimentoView.as_view(), name='inserimento'),
    path('evento/<int:pk>/modifica', ModificaEventoView.as_view(), name='evento-modifica'),
    path('evento/<int:pk>/elimina', EliminaEventoView.as_view(), name='evento-elimina'),
    path('status/<int:pk>', StatusView.as_view(), name='status'),
    path('classifica/<int:pk>/squadre', ClassificaView.as_view(), name='classifica-squadre'),
    path('classifica/<int:pk>/problemi', PuntiProblemiView.as_view(), name='classifica-problemi'),
    path('classifica/<int:pk>/stato', StatoProblemiView.as_view(), name='classifica-stato'),
    path('classifica/<int:pk>/unica', UnicaView.as_view(), name='classifica-unica'),
    path('classifica/<int:pk>/scorrimento', ScorrimentoView.as_view(), name='classifica-scorrimento'),
    path('about', AboutView.as_view(), name="about"),
    path('now', NowView.as_view(), name="now")
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

turing/engine/models.py
from django.db import models
from django.core.exceptions import ValidationError, PermissionDenied
from django.core.validators import MaxValueValidator
from django.utils import timezone, dateparse
from django.contrib.auth.models import AbstractUser
from simple_history.models import HistoricalRecords

from datetime import timedelta, date, time
import json
import uuid
from dateutil.parser import parse

import logging
logger = logging.getLogger(__name__)

from string import Template
from django.conf import settings
import pytz
TIME_ZONE_SETTING = getattr(settings, "TIME_ZONE", None)
assert TIME_ZONE_SETTING is not None
assert isinstance(TIME_ZONE_SETTING, str)
TIME_ZONE_SETTING = pytz.timezone(TIME_ZONE_SETTING)


class DeltaTemplate(Template):
    delimiter = "%"

def strfdelta(tdelta, fmt):
    d = {"D": tdelta.days}
    hours, rem = divmod(tdelta.seconds, 3600)
    minutes, seconds = divmod(rem, 60)
    d["H"] = '{:02d}'.format(hours)
    d["M"] = '{:02d}'.format(minutes)
    d["S"] = '{:02d}'.format(seconds)
    t = DeltaTemplate(fmt)
    return t.substitute(**d)


def get_file_path(instance, filename):  # pragma: no cover
    ext = filename.split('.')[-1]
    filename = "%s.%s" % (uuid.uuid4(), ext)
    return 'testi/'+filename


def str2arr(s):
    if s == "":
        return []
    return [int(x) for x in s.split(',')]


def all_nonnegative_validator(val):
    arr = str2arr(val)
    if not all(x>=0 for x in arr):
        raise ValidationError("Gli interi devono essere tutti non negativi")

class User(AbstractUser):
    GENDERS = (
        ('M', 'Maschio'),
        ('F', 'Femmina'),
        ('N', 'Non specificato'),
    )
    gender = models.CharField(max_length=1, choices=GENDERS, default='N', verbose_name='Genere')

    def can_administrate(self, gara):
        return gara.admin == self

    def is_inseritore(self, gara):
        return self in gara.inseritori.all()

    def is_consegnatore(self, gara):
        return Squadra.objects.filter(gara=gara, consegnatore=self).exists()

    def can_insert_gara(self, gara):
        """Controlla che l'utente sia un admin, un inseritore o un consegnatore"""
        return self.can_administrate(gara) or self.is_inseritore(gara) or self.is_consegnatore(gara)

    def can_insert_squadra(self, squadra):
        """Controlla che l'utente sia un admin, un inseritore o un consegnatore"""
        return self.can_administrate(squadra.gara) or self.is_inseritore(squadra.gara) or squadra.consegnatore == self

    def can_edit_or_delete(self, evento):
        """Controlla che l'utente sia admin, o un inseritore proprietario dell'evento."""
        return self.can_administrate(evento.gara) or (self.is_inseritore(evento.gara) and evento.creatore == self)

    def can_create_gara(self):
        return self.has_perm("engine.change_gara")

class Gara(models.Model):
    """
    Modello che descrive una gara
    """
    nome = models.CharField(max_length=200, help_text="Nome della gara")
    inizio = models.DateTimeField(blank=True, null=True)
    sospensione = models.DateTimeField(blank=True, null=True)
    durata = models.DurationField(default=timedelta(hours=2), help_text="Durata nel formato hh:mm:ss")
    n_blocco = models.PositiveSmallIntegerField(blank=True, default=2, null=True,  # Il valore NULL non fa bloccare mai il punteggio
                                                verbose_name="Parametro N",
                                                help_text="Numero di risposte esatte che bloccano il punteggio di un problema")
    k_blocco = models.PositiveSmallIntegerField(blank=True, default=1, null=True,  # Il valore NULL fa aumentare sempre il punteggio
                                                verbose_name="Parametro K",
                                                help_text="Numero di risposte errate che aumentano il punteggio di un problema")
    durata_blocco = models.DurationField(default=timedelta(minutes=20), help_text="Il punteggio dei problemi viene bloccato quando il tempo rimanente è quello indicato in questo campo nel formato hh:mm:ss")
    num_problemi = models.PositiveSmallIntegerField(default=20,
                                                    verbose_name="Problemi",
                                                    help_text="Numero di problemi")
    punteggio_iniziale_squadre = models.PositiveSmallIntegerField(blank=True, null=True, help_text="Punteggio iniziale per ciascuna squadra. Se lasciato bianco, il punteggio è pari al numero di quesiti moltiplicato per 10 (dove -10 corrisponde alla penalità per una risposta errata)")
    fixed_bonus = models.CharField(blank=True, max_length=100,
                                   default='20,15,10,8,6,5,4,3,2,1',
                                   validators=[all_nonnegative_validator],
                                   verbose_name="Bonus problema",
                                   help_text="Bonus per le prime squadre a risolvere un problema")
    super_mega_bonus = models.CharField(blank=True, max_length=100,
                                        default='100,60,40,30,20,10',
                                        validators=[all_nonnegative_validator],
                                        verbose_name="Bonus finale",
                                        help_text="Bonus per le prime squadre a risolvere tutti i problemi")
    jolly = models.BooleanField(default=True,
                                verbose_name="Jolly",
                                help_text="Possibilità di inserire un jolly")
    history = HistoricalRecords()

    #
    # Permessi
    #

    admin = models.ForeignKey(User, on_delete=models.CASCADE, related_name="administered_gare", null=True)
    inseritori = models.ManyToManyField(User, blank=True)

    class Meta:
        verbose_name_plural = "gare"

    def __str__(self):
        return self.nome

    """
    Definisce delle proprietà in modo da poter ottenere e settare direttamente
    degli array per i bonus di risoluzione dei problemi
    """

    def get_fixed_bonus_array(self):
        return str2arr(self.fixed_bonus)

    def set_fixed_bonus_array(self, array):
        self.fixed_bonus = ','.join(map(str, array))

    fixed_bonus_array = property(get_fixed_bonus_array, set_fixed_bonus_array)

    def get_super_mega_bonus_array(self):
        return str2arr(self.super_mega_bonus)

    def set_super_mega_bonus_array(self, array):
        self.super_mega_bonus = ','.join(map(str, array))

    super_mega_bonus_array = property(get_super_mega_bonus_array, set_super_mega_bonus_array)

    def get_ora_fine(self):
        if not self.inizio:
            return None
        if self.sospensione:
            return None
        return self.inizio + self.durata

    def get_ora_blocco(self):
        if not self.inizio:
            return None
        if self.sospensione:
            return None
        return self.inizio + self.durata - self.durata_blocco

    def finished(self):
        return (self.inizio is not None) and (self.sospensione is None) and (timezone.now() > self.get_ora_fine())

    def get_all_eventi(self, user, id_evento, num_squadra, problema, risposta):
        """Restituisce tutti gli eventi all'amministratore."""
        qs = self.eventi.all().select_related("consegna__squadra", "jolly__squadra", "bonus__squadra")

        if user.can_administrate(self):

            res = [x.as_child() for x in qs]
            for x in res:
                x.timestamp = strfdelta(x.orario - self.inizio, "%H:%M:%S")
                if hasattr(x, "problema") and hasattr(x, "risposta"):
                    x.giusta = (x.risposta == self.soluzioni.get(problema=x.problema).risposta)
                else:
                    x.giusta = None
            if id_evento:
                res = [x for x in res if x.pk == int(id_evento)]
            if num_squadra:
                res = [x for x in res if x.squadra.num == int(num_squadra)]
            if problema:
                if problema == "B":
                    res = [x for x in res if isinstance(x, Bonus)]
                else:
                    assert problema.isdigit()
                    res = [x for x in res if hasattr(x, "problema") and x.problema == int(problema)]
            if risposta:
                if risposta == "J":
                    res = [x for x in res if isinstance(x, Jolly)]
                else:
                    if risposta == "G":
                        res = [x for x in res if hasattr(x, "risposta") and x.giusta]
                    elif risposta == "S":
                        res = [x for x in res if hasattr(x, "risposta") and not x.giusta]
                    else:
                        assert risposta.isdigit()
                        res = [x for x in res if hasattr(x, "risposta") and x.risposta == int(risposta)]

            return res
        raise PermissionDenied("L'utente non può chiedere gli eventi della gara.")

    def get_eventi_recenti(self, user, limit):
        """Restituisce gli eventi visualizzabili dall'utente."""
        qs = self.eventi.all().select_related("consegna__squadra", "jolly__squadra", "bonus__squadra")

        if user.can_administrate(self):
            return [(True, x.as_child()) for x in qs[:limit]]
        if user.is_inseritore(self):
            return [(x.creatore == user, x.as_child()) for x in qs[:limit]]
        if user.is_consegnatore(self):
            return [(False, x.as_child()) for x in qs.filter(creatore=user)[:limit]]
        raise PermissionDenied("L'utente non può chiedere gli eventi della gara.")

    def get_squadre_inseribili(self, user):
        '''Restiuisce le squadre per cui l'utente può effettuare una consegna.'''
        qs = self.squadre.all()
        if user.can_administrate(self) or user.is_inseritore(self):
            return qs
        else:
            qs = qs.filter(consegnatore=user)
            if qs.exists():
                return qs
            else:

turing/engine/templates/about.html
{% extends "baseheader.html" %}

{% block title %}About{% endblock %}

{% block content %}
<h1>About</h1>

<p>Turing è un software open source per la gestione delle gare a squadre di Matematica.</p>
<p>Il nostro obiettivo è quello di rendere semplice e disponibile a tutti l'utilizzo di un motore per le gare a squadre. Sai che questo sito potrebbe girare senza problemi anche sul tuo computer?</p>

<h2>Il progetto</h2>

<p>
    Questo sito è sicuramente l'elemento più visibile di questo progetto, ma la parte fondamentale è la community che vorremmo creare.<br/>
    Puoi venirci a trovare:
    <ul>
        <li>su <a href="https://discord.gg/gMgJmPukUA" target="_blank">Discord</a>, per parlare con altri di Turing e di gare a squadre</li>
        <li>su <a href="https://gitlab.com/drago-96/turing" target="_blank">GitLab</a>, se sei interessato anche all'aspetto di sviluppo del programma</li>
    </ul>
</p>


<h2>Chi siamo</h2>

<p>Il team di sviluppatori è composto da Riccardo Zanotto, Matteo Migliorini, Federico Poloni, Matteo Protopapa e Matteo Rossi.</p>

<h2>Versione personalizzata</h2>

<p>Questa installazione è basata su <a href="https://github.com/dmf-unicatt/turing-dmf" target="_blank">Turing @ DMF</a>, una versione personalizzata di Turing per le esigenze specifiche del <a href="https://www.dmf.unicatt.it/" target="_blank">Dipartimento di Matematica e Fisica</a>, <a href="https://www.unicatt.it/" target="_blank">Università Cattolica del Sacro Cuore</a>. Il contatto locale è il <a href="https://www.francescoballarin.it/" target="_blank">Prof. Francesco Ballarin</a>.</p>

{% endblock %}

turing/engine/templates/base.html
<!DOCTYPE html>
<html lang="it">
{%load static%}
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>{% block title %}{% endblock %}</title>

    <!-- Bootstrap & jQuery -->
    <script src="{% static 'vendor/jquery/jquery.min.js' %}"></script>
    <script src="{% static 'vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>

    <link href="{% static 'vendor/fontawesome-free/css/all.min.css' %}" rel="stylesheet" type="text/css">
    <link href="{% static 'vendor/SB_Admin/css/sb-admin.css' %}" rel="stylesheet" type="text/css">


    <link href="{% static 'engine/css/main.css' %}" rel="stylesheet" type="text/css" >

    {% block css %}{% endblock %}
    {% block head %}{% endblock %}
</head>
<body class="d-flex flex-column min-vh-100">
  {% block header %}{% endblock %}
    <div class="flex-fill container-fluid">
        {% if messages %}
        <ul class="messages">
            {% for message in messages %}
            <div class="alert alert-{{message.tags}} alert-dismissible fade show" role="alert">
              {{message}}
              <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                <span aria-hidden="true">&times;</span>
              </button>
            </div>
            {% endfor %}
        </ul>
        {% endif %}
    {% block content %}{% endblock %}
    </div>
    {% block footer %}{% endblock %}
    <script>
    window.onerror = function(msg, url, linenumber) {
      alert('Error message: '+msg+'\nURL: '+url+'\nLine Number: '+linenumber);
      return true;
    }
    </script>
</body>
</html>

turing/engine/templates/basegara.html
{% extends "baseheader.html" %}
{% block navitems %}
{% if object %}
<li class="nav-item dropdown">
  <a class="nav-link" href="{% url 'engine:gara-detail' object.pk %}">
    {{object.nome}} overview <i class="fas fa-home"></i>
  </a>
</li>
{% if not object.finished %}
<li class="nav-item dropdown">
    <a class="nav-link" href="{% url 'engine:inserimento' object.pk %}">
        Inserimento <i class="fas fa-edit"></i>
    </a>
</li>
{% endif %}

<li class=" nav-item dropdown">
  <button type="button" class="btn nav-link dropdown-toggle" data-toggle="dropdown" aria-haspopup="true">
    Classifiche <i class="fas fa-bars" style="color:gray"></i>
  </button>
  <ul class="dropdown-menu dropdown-menu-right bg-dark text-white">
    <li><a class="text-white" href="{% url 'engine:classifica-squadre' object.pk %}" target="_blank">Squadre</a></li>
    <li><a class="text-white" href="{% url 'engine:classifica-problemi' object.pk %}" target="_blank">Problemi</a></li>
    <li><a class="text-white" href="{% url 'engine:classifica-stato' object.pk %}" target="_blank">Stato</a></li>
    {% if object.inizio is not null and object.sospensione is null %}
    <li><a class="text-white" href="{% url 'engine:classifica-unica' object.pk %}" target="_blank">Unica</a></li>
    <li><a class="text-white" href="{% url 'engine:classifica-scorrimento' object.pk %}" target="_blank">A scorrimento</a></li>
    {% endif %}
  </ul>
</li>
{% endif %}
{% endblock %}

turing/engine/templates/baseheader.html
{% extends "base.html" %}
{%load static%}
{% block header %}
  <nav class="navbar navbar-expand-lg navbar-dark bg-dark static-top">
    <a class="navbar-brand mr-1 text-truncate" style="max-width:75%" href="/engine/">
        <img src="{% static 'logo.png' %}" class="img-thumbnail" style="height:2.5rem"></img>
        <span class="ml-2">Turing - Gestione Gara a Squadre</span>
    </a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav ml-auto mr-0 mr-md-3 my-2 my-md-0">

          {% block navitems %}
          {% if gare_attive %}
          <li class="nav-item dropdown">
              <button type="button" class="btn nav-link dropdown-toggle" data-toggle="dropdown" aria-haspopup="true">
                Gare attive <i class="fas fa-bars" style="color:gray"></i>
              </button>
            <ul class="dropdown-menu dropdown-menu-right bg-dark text-white">
              {% for g in gare_attive %}
              <li><a class="text-white" href="{% url 'engine:gara-detail' g.pk %}">{{g}}</a></li>
              {% endfor %}
            </ul>
          </li>
          {% endif %}
          {% endblock %}

          <li class="nav-item dropdown">
            {% if user.is_authenticated %}
              <button type="button" class="btn nav-link dropdown-toggle" data-toggle="dropdown" aria-haspopup="true">
                {{ user.first_name }} <i class="fas fa-user" style="color:gray"></i>
              </button>
              <ul class="dropdown-menu dropdown-menu-right bg-dark text-white">
                {% if user.is_staff %}
                <li><a class="text-white" href="{% url 'admin:index' %}" target="_blank">Admin <i class="fas fa-user-circle"></i></a></li>
                {% endif %}
                {% if user.can_create_gara %}
                <li><a class="text-white" href="{% url 'engine:gara-new' %}">Nuova gara  <i class="fas fa-plus-circle"></i></a></li>
                {% endif %}
                <li><a class="text-white" href="{% url 'password_change' %}">Cambio password <i class="fas fa-key"></i></a></li>
                <li><form id="logout-form" action="{% url 'logout' %}" method="post">
                    {% csrf_token %}
                    <button class="text-white" type="submit">Logout <i class="fas fa-sign-out-alt"></i></button>
                </form>
              </ul>
            {% else %}
            {% if registration_open %}
              <a class="nav-link" href="{% url 'signup' %}">
                Registrati <i class="fas fa-user-plus"></i>
              </a>
              </li>
            {% endif %}
              <li class="nav-item dropdown">
              <a class="nav-link" href="{% url 'login' %}">
                Login <i class="fas fa-sign-in-alt"></i>
              </a>
            {% endif %}
          </li>
        </ul>
    </div>
  </nav>
{% endblock %}
{% block footer %}
    <footer class="font-small text-light bg-dark mt-3 py-1 pl-2">
        <div class="pull-left">
          Powered by <a href="{% url 'engine:about' %}">Turing</a> (customized by <a href="https://github.com/dmf-unicatt/turing-dmf">Turing @ DMF</a>).
        </div>
    </footer>
{% endblock %}

turing/engine/templates/index.html
{% extends "baseheader.html" %}

{% block title %}Turing homepage{% endblock %}

{% block content %}

{% if gare_attive %}
<div id="wrapper">
  <div class="card mb-3">
    <div class="card-header">
      <h5 class="pr-3"><i class="fas fa-table"></i>
      Gare in corso</h5>
    </div>
    <div class="card-body">
      <div class="table-responsive">
        <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
          <thead>
            <tr>
              <th>Id</th>
              <th>Nome</th>
              <th>Inizio</th>
              <th>Fine</th>
              {% if user.is_staff %}
              <th>Download</th>
              <th>Sospendi/Riprendi</th>
              <th>Reset</th>
              <th>Cancella</th>
              {% endif %}
            </tr>
          </thead>
          <tbody>
              {% for gara in gare_attive %}
            <tr>
              <td>{{gara.pk}}</td>
              <td><a href="{% url 'engine:gara-detail' gara.pk%}">{{gara.nome}}</a></td>
              <td>{{gara.inizio}}</td>
              {% if gara.sospensione is null %}
              <td>{{gara.get_ora_fine}}</td>
              {% else %}
              <td>Temporaneamente sospesa</td>
              {% endif %}
              {% if user.is_staff %}
              <td><a href="{% url 'engine:gara-download' gara.pk%}" target=_blank><i class="fas fa-download" title="Download gara"></i></a></td>
              {% if gara.sospensione is null %}
              <td><a href="{% url 'engine:gara-pause' gara.pk%}" target=_blank><i class="fas fa-pause" title="Sospendi gara"></i></a></td>
              {% else %}
              <td><a href="{% url 'engine:gara-resume' gara.pk%}" target=_blank><i class="fas fa-play" title="Riprendi gara"></i></a></td>
              {% endif %}
              <td><a href="{% url 'engine:gara-reset' gara.pk%}" target=_blank><i class="fas fa-undo" title="Reset gara"></i></a></td>
              <td><a href="{% url 'engine:gara-delete' gara.pk%}" target=_blank><i class="fas fa-trash" title="Cancella gara"></i></a></td>
              {% endif %}
            </tr>
            {% endfor %}
          </tbody>
        </table>
      </div>
    </div>
  </div>
</div>
{% endif %}

<div id="wrapper">
  <div class="card mb-3">
    <div class="card-header">
      <div class="d-flex align-items-baseline justify-content-between">
        <h5 class="pr-3"><i class="fas fa-table"></i> Gare da iniziare</h5>
        {% if perms.engine.add_gara %}
          <div><a href="{% url 'engine:gara-new' %}" class="btn btn-primary">Crea nuova gara</a></div>
        {% endif %}
      </div>
    </div>
    <div class="card-body">
      <div class="table-responsive">
        <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
          <thead>
            <tr>
              <th>Id</th>
              <th>Nome</th>
              {% if user.is_staff %}
              <th>Download</th>
              <th>Inizia</th>
              <th>Reset</th>
              <th>Cancella</th>
              {% endif %}
            </tr>
          </thead>
          <tbody>
              {% for gara in gare_da_iniziare %}
            <tr>
              <td>{{gara.pk}}</td>
              <td><a href="{% url 'engine:gara-detail' gara.pk%}">{{gara.nome}}</a></td>
              {% if user.is_staff %}
              <td><a href="{% url 'engine:gara-download' gara.pk%}" target=_blank><i class="fas fa-download" title="Download gara"></i></a></td>
              <td><a href="{% url 'engine:gara-admin' gara.pk%}" target=_blank><i class="fas fa-play" title="Inizia gara"></i></a></td>
              <td><a href="{% url 'engine:gara-reset' gara.pk%}" target=_blank><i class="fas fa-undo" title="Reset gara"></i></a></td>
              <td><a href="{% url 'engine:gara-delete' gara.pk%}" target=_blank><i class="fas fa-trash" title="Cancella gara"></i></a></td>
              {% endif %}
            </tr>
            {% endfor %}
          </tbody>
        </table>
      </div>
    </div>
  </div>
</div>

<div id="wrapper">
  <div class="card mb-3">
    <div class="card-header">
      <div class="d-flex align-items-baseline justify-content-between">
        <h5 class="pr-3"><i class="fas fa-table"></i> Archivio</h5>
        {% if perms.engine.add_gara %}
          <div><a href="{% url 'engine:gara-upload' %}" class="btn btn-primary">Importa gara</a></div>
        {% endif %}
      </div>
    </div>
      <div class="card-body">
        <div class="table-responsive">
          <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
            <thead>
              <tr>
                <th>Id</th>
                <th>Nome</th>
                <th>Inizio</th>
                <th>Fine</th>
                {% if user.is_staff %}
                <th>Download</th>
                <th>Reset</th>
                <th>Cancella</th>
                {% endif %}
              </tr>
            </thead>
            <tbody>
                {% for gara in gare_archivio %}
              <tr>
              <td>{{gara.pk}}</td>
              <td><a href="{% url 'engine:gara-detail' gara.pk%}">{{gara.nome}}</a></td>
                <td>{{gara.inizio}}</td>
                <td>{{gara.get_ora_fine}}</td>
                {% if user.is_staff %}
                <td><a href="{% url 'engine:gara-download' gara.pk%}" target=_blank><i class="fas fa-download" title="Download gara"></i></a></td>
                <td><a href="{% url 'engine:gara-reset' gara.pk%}" target=_blank><i class="fas fa-undo" title="Reset gara"></i></a></td>
                <td><a href="{% url 'engine:gara-delete' gara.pk%}" target=_blank><i class="fas fa-trash" title="Cancella gara"></i></a></td>
                {% endif %}
              </tr>
              {% endfor %}
            </tbody>
          </table>
        </div>
      </div>
  </div>
</div>
{% endblock %}

turing/engine/templates/now.html
{% now "c" %}